### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by ruisimoes** [Zimbra-Community/com_zimbra_stickynotes#1]
When the webmail is defined to Portuguese_Portugal stickynotes don't work properly.

![stickynotes](https://cloud.githubusercontent.com/assets/12556698/11776410/c4055794-a23e-11e5-85c7-70c3a44c3b68.png)

**Comment by ghost** [comment]
please try with this version:
https://github.com/Zimbra-Community/com_zimbra_stickynotes/files/60938/com_zimbra_stickynotes.zip
Is the latest release.

Then on the server:
 zmprov fc all 

And flush your browser cache, I suspect then it will show in english in the preferences pane, but the tag and other components are translated.

**Comment by ghost** [comment]
Looks like one needs to add:
description =
to com_zimbra_stickynotes/com_zimbra_stickynotes_pt.properties

And also do that in all other languages, it appears the preferences pane was never translated.

@ruisimoes Is the current version workable for you?

**Comment by ruisimoes** [comment]
I made the changes but is the first time I do something in the github and i
don't know if a done something wrong.

If you want I'm available to translate for Portuguese_Portugal.

2015-12-14 9:22 GMT+00:00 Barry de Graaff notifications@github.com:

**Comment by ghost** [comment]
Looks like you did fine, also there is not much to translate in this Zimlet, since I removed the preferences.

So we should be good now.

**Comment by ruisimoes** [comment]
Maybe in other zimlets.

2015-12-14 9:50 GMT+00:00 Barry de Graaff notifications@github.com:

**Comment by ghost** [comment]
OK thanks!
