### ISSUE TITLE
Pop Up message 

### ISSUE THREAD

**Issue by Copyrght** [Zimbra-Community/com_zimbra_stickynotes#10]
Hi. How can i add proper pop up message for sticky notes. I got messages like - ' 1 message tagged "" ' and ' tag "" removed from 1 message '

Zimbra 8.8.12_GA_3844 (build 20190819064612)

**Comment by ghost** [comment]
this is fixed in version https://github.com/Zimbra-Community/com_zimbra_stickynotes/releases/tag/2.2.0
