### ISSUE TITLE
Error on Contacts-Distribution lists

### ISSUE THREAD

**Issue by timur-g** [Zimbra-Community/com_zimbra_stickynotes#3]
When StickyNotes is active and I click on Contacts-Distribution lists, I get this error:
"Warning
	TypeError: e.getResponse(...).BatchResponse.GetCustomMetadataResponse is undefined"

Reproduced with ZCS 8.7.1. which says:
Zimlet com_zimbra_stickynotes
         Version: 1.8
     Description: ${msg.description}

**Comment by ghost** [comment]
Thanks for reporting, new version release to fix this issue.

**Comment by timur-g** [comment]
I installed corrected version 1.9 and and it's: 
Zimlet com_zimbra_stickynotes
         Version: 1.9
     Description: ${msg.description}

Unless some service needs to be restarted, I still get (after I signed out and in as a user): 
TypeError: e.getResponse(...).BatchResponse.GetCustomMetadataResponse is undefined

**Comment by ghost** [comment]
Yeah, that is cache,

on the server:
 zmprov fc all

flush your browser cache

**Comment by timur-g** [comment]
Right. It's OK now. Thank you.

**Comment by ghost** [comment]
Please take a moment to leave a review on:
https://zimbra.org/extend/items/view/sticky-notes
