### ISSUE TITLE
Confirmation before deleting...

### ISSUE THREAD

**Issue by DavidWMerrill** [Zimbra-Community/com_zimbra_stickynotes#4]
...is there a convention for prompting the user to confirm when they click on the red x?

**Comment by ghost** [comment]
Hello David,

A delete confirmation dialog has been added, 
https://github.com/Zimbra-Community/com_zimbra_stickynotes/tree/2.1

**Comment by DavidWMerrill** [comment]
Thanks! I'll give it a go today.

**Comment by DavidWMerrill** [comment]
Thanks again, the confirmation works great.
