### ISSUE TITLE
Moving the sticky note around?

### ISSUE THREAD

**Issue by DavidWMerrill** [Zimbra-Community/com_zimbra_stickynotes#7]
Is it possible to move the sticky note around? From what I can glean from the code I think it's a div element? I've only ever dabbled in JavaScript (mostly form element validations), but I found this on a quick search:

 - https://www.kirupa.com/snippets/move_element_to_click_position.htm

Ha, now I'm becoming feature-request-guy (and that's NOT me), I'd love to contribute, but I know nothing practical of JavaScript (so far).

so really just curious would adding that kind of feature be a lot of work (& refactoring)?

**Comment by ghost** [comment]
No that should not be much work, the calendar bug we have zimlet atm is :-p

**Comment by DavidWMerrill** [comment]
I hear that, good luck!
